server:
  port: 0
spring:
  application:
    name: msa-app-order
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: msa-app-order
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1234
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
  zipkin:
    base-url: http://localhost:9411
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0 # 100% 일단 설정

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defautZone: http://localhost:8761/eureka

logging:
  level:
    com.example.msaapporder: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, prometheus, metrics
