# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    volumes:
      - ./varlibmysql:/var/lib/mysql
    ports:
      - 3306:3306